config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'pages#index'
  root 'pages#index'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => 'sessions#destroy', as: :signout
  get "/signin" => 'sessions#new', as: :signin

  resources :user_tasks, path: 'tasks'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_tasks

  # Create user using the hash that's returned from the Facebook API
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

  # Pulls over the current facebook profile avatar
  def small_image
    "http://graph.facebook.com/#{self.uid}/picture?type=small"
  end

  # Pulls over the current facebook profile normal sized image
  def normal_image
    "http://graph.facebook.com/#{self.uid}/picture?type=normal"
  end
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # We can declare a helper method here to make it available to all views and controllers
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    redirect_to :signin unless current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    auth = request.env["omniauth.auth"]

    # Rails magic!  Go look in our database for a user with that provider and uid. If they don't exist yet, create them.
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

    # Go set the session user_id
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in successfully!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out successfully!"
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :authenticate!
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_task

  # GET /user_tasks
  # GET /user_tasks.json
  def index
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)
    @user_task.user_id = current_user.id

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    def all_tasks
      @user_tasks = UserTask.where(user_id: current_user.id).order(:due)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])

      if current_user.id == @user_task.user_id
        @user_task
      else
        invalid_task
      end
    end

    def invalid_task
      logger.error "Attempt to access invalid task #{params[:id]}."
      redirect_to user_tasks_url, notice: 'Invalid task'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to fa_icon('list', text: 'Tasks'), user_tasks_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to fa_icon('sign-out', text: 'Sign Out'), signout_path, id: "sign_out" %></li>
          <li><%= image_tag current_user.small_image, class: "user-thumb" %></li>
        <% else %>
          <li><%= link_to fa_icon('sign-in', text: 'Sign in with Facebook'), "/auth/facebook", id: "sign_in" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function() {
  $('#user_task_due').datepicker({
    format: "yyyy-mm-dd",
    todayBtn: "linked",
    orientation: "top auto",
    autoclose: true,
    todayHighlight: true
  });
});

app/views/user_tasks/_form.html.erb
<div class="well">
  <%= simple_form_for(@user_task, remote: true) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :description, placeholder: "Make groceries." %>
      <%= f.input :due, as: :string, placeholder: "Today!" %>
    </div>

    <div class="form-actions text-right">
      <%= f.button :button, fa_icon('floppy-o', text: 'Save'), class: 'btn btn-success' %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    </div>
  <% end %>
</div>

app/views/user_tasks/_user_task.html.erb
<div class="well">
  <span class='pull-right text-muted'>
    <small><em><%= user_task.due.try(:stamp, 'December 1, 2015') %></em></small>
  </span>

  <span class="task">
    <%= link_to user_task.description, user_task, remote: true, method: :delete, data: {confirm: 'Are you sure?'} %>
  </span>

  <%= link_to fa_icon('pencil'), edit_user_task_path(user_task), remote: true %>
</div>

app/views/user_tasks/create.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");
$('#task-form').slideUp(350);
$('#add-task-button').show()

app/views/user_tasks/destroy.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-sm-4 form-box">
    <p class="text-right">
      <%= link_to fa_icon('plus', text: 'Add Task'), new_user_task_path, remote: true, class: 'btn btn-primary', id: 'add-task-button' %>
    </p>

    <div id="task-form"></div>
  </div>

  <div class="col-sm-8">
    <h2>My Tasks</h2>
    <div id="tasks">
      <%= render @user_tasks %>
    </div>
  </div>

</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#add-task-button').hide();
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

<%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");
$('#task-form').slideUp(350);